services:
  flask:
    build: . # Build the image from the Dockerfile in the current directory
    container_name: flask_app
    ports:
      - "5000:5000"
      - "8080:8080"
    depends_on:
      - mongo
      - mysql
      - redis
    environment:
      PYTHONPATH: /app/data_processing

      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456

      MYSQL_HOST: mysql # prior than .env
      MYSQL_ROOT_PASSWORD: 110110
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+pymysql://root:110110@mysql:3306/airflow?charset=utf8mb4

      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__CORE__DAGS_FOLDER: /app/data_processing/my_custom_dags

      REDIS_URL: redis://redis:6379/0
    restart: always
    volumes:
      - .:/app
      - airflow_dags:/app/data_processing/my_custom_dags
      - airflow_logs:/usr/local/airflow/logs
      - airflow_plugins:/usr/local/airflow/plugins

  mongo:
    image: mongo
    container_name: mongo_server
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - mongo_data:/data/db

  mysql:
    image: mysql:8.0
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 110110
    volumes: 
      - web_mysql_data:/var/lib/mysql
      - D:/Personal_Experience/news_brain/mysql_init:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    container_name: redis_server
    restart: always
    expose:
      - "6379"

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx_server
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - flask
  #   restart: always

volumes:
  web_mysql_data:
  mongo_data:
  airflow_dags:
  airflow_logs:
  airflow_plugins: